### ISSUE TITLE
Serverless Package and final artifact

### ISSUE THREAD

**Issue by romainquellec** [danielcondemarin/serverless-nextjs-plugin#11]
With my current project : https://github.com/CuistotduCoin/front

If I do this : serverless package
In .serverless/serverless-ssr.zip contain everything in the directory. I think it should only contain "sls-next-build". This is a bug, right ?

If not, what I'm doing wrong ?

**Comment by danielcondemarin** [comment]
Excluding stuff is up to the user. The plugin only makes sure that the page handlers are always **included**.

I would normally exclude everything, for example:

```yml
plugins:
  - serverless-nextjs-plugin

custom:
  serverless-nextjs:
    nextConfigDir: "./"

package:
  exclude:
    - ./**/*
```

**Comment by romainquellec** [comment]
That's what I do.

**Comment by romainquellec** [comment]
Right now, .serverless/serverless-ssr.zip is 226 Mo.
I'm almost at the limit fixed by AWS.

**Comment by romainquellec** [comment]
What I did, (i dont know if this is correct) : 
```
package:
  exclude:
    - ./**
  include:
    - .serverless/**`
```
