### ISSUE TITLE
Public asset returns 404

### ISSUE THREAD

**Issue by barrysteyn** [danielcondemarin/serverless-nextjs-plugin#130]
Hi All

I am using version 2.3.3 of this plugin. I have a public folder with a file (file === hello.txt, content is hello world), however whenever I try serve that file, I get a 404. @danielcondemarin and @mattdell you can see a demonstration of this by going to https://sayy.it/hello.txt

Here is my setup:
```
service: sayyit-frontend

plugins:
  - serverless-nextjs-plugin
  - serverless-domain-manager
  - serverless-plugin-warmup
  - serverless-offline

custom:
  stage: ${self:provider.stage}
  memorySize: 256
  prefixes:
    RESOURCES_PREFIX: ${self:service.name}-${self:provider.stage}
  serverless-nextjs:
    cloudFrontConfig:
      prod:
        cloudFront: true
        assetsBucketName: sayyit-prod-static-assets
    assetsBucketName: ${self:custom.serverless-nextjs.cloudFrontConfig.${self:custom.stage}.assetsBucketName}
    cloudFront: ${self:custom.serverless-nextjs.cloudFrontConfig.${self:custom.stage}.cloudFront}
    nextConfigDir: ./
    staticDir: ./static
    customHandler: ./lambda-handler.js  
    routes:
      - src: category
        path: category/{id}/{slug}
        request:
          parameters:
            paths:
              id: true
              slug: true
      - src: topic
        path: topic/{id}/{slug}
        request:
          parameters:
            paths:
              id: true
              slug: true
      - src: profile
        path: profile/{id}/{slug}
        request:
          parameters:
            paths:
              id: true
              slug: true
  customDomain:
    staging:
      staging.sayy.it
    prod:
      sayy.it
    domainName: ${self:custom.customDomain.${self:custom.stage}}
    basePath: ''
    stage: ${self:custom.stage}
    createRoute53Record: true
  warmup:
    enabled: prod # Whether to warm up functions by default or not
    folderName: '_warmup' # Name of the folder created for the generated warmup
    cleanFolder: false
    memorySize: ${self:custom.memorySize}
    vpc: false
    events:
      - schedule: 'rate(10 minutes)' # Run WarmUp every 10 minutes
    timeout: 20
    prewarm: true # Run WarmUp immediately after a deploymentlambda
    concurrency: 10 # Warm up 10 concurrent instances

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: ${self:custom.memorySize}
  timeout: 10
  stage: ${env:STAGE, 'staging'}
  tags:
    SERVICE: ${self:custom.prefixes.RESOURCES_PREFIX}
  region: ${opt:region, 'us-east-1'}
  iamRoleStatements:
    # Lambda Warmup functions
  - Effect: 'Allow'
    Action:
      - 'lambda:InvokeFunction'
    Resource:
    - Fn::Join:
      - ':'
      - - arn:aws:lambda
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - function:${self:service}-${self:provider.stage}-*

package:
  exclude:
    - ./**/*
```
What am I doing wrong?
