### ISSUE TITLE
Configure multiple URLs to be served by the same page (file)

### ISSUE THREAD

**Issue by ematipico** [danielcondemarin/serverless-nextjs-plugin#44]
Hi, I am new to this plugin and to the `serverless` ecosystem, so maybe this is not the best place to ask this question.

My use case is that I have a page that serves different URLs. Let's call the page `content.js` which is the real file. How can I setup `serverless.yml` in order to handle different URLs? For example
- `blog/{url}` => rendered by `content.js`
- `meetings/{url}` => rendered by `content.js`
- `info/{url}`  => rendered by `content.js`

Amazing plugin btw!!! Thanks!

**Comment by ematipico** [comment]
I found out how! 

```yml
	content:
        events:
          - http:
              method: get
              path: blog/{url}
              request:
                parameters:
                  paths:
                    url: true   
          - http:
              method: get
              path: meetings/{url}
              request:
                parameters:
                  paths:
                    url: true 
          - http:
              method: get
              path: info/{url}
              request:
                parameters:
                  paths:
                    url: true  

```
