### ISSUE TITLE
Feature: Improved page and static resources Routing

### ISSUE THREAD

**Issue by danielcondemarin** [danielcondemarin/serverless-nextjs-plugin#51]
## Motivation

Currently there are no routing capabilities for static assets. For example, you can't have `/robots.txt`, `/browserconfig.xml` or maybe a service worker `/sw.js`. 
Also, although the custom routing for pages works and is flexible it can be quite verbose to declare:

```yml
custom:
  serverless-nextjs:
    nextConfigDir: ./
    pageConfig:
      post:
        events:
          - http:
              path: post/{slug}
              request:
                parameters:
                  paths:
                    slug: true 
```
That is just for a custom post page route: `post/{slug}`.

# Proposal

1 - Upload `static/` directory contents to S3 assets bucket

The concept of a static folder is familiar already to next developers. Is an easy way to get static content available to the application. The plugin already manages an S3 bucket where the next build assets are uploaded, so the `static/` dir contents will also be uploaded to the same bucket.

2 - Add support for a new `routes` plugin configuration array:

```yml
# serverless.yml
custom:
  serverless-nextjs:
    nextConfigDir: ./
    routes:
       -
          # post page routing
          # https://123.execute-api.us-east-1.amazonaws.com/dev/post/123
          src: pages/post.js
          path: post/{slug}
          request:
            parameters:
              paths:
                slug: true
       -
          # https://123.execute-api.us-east-1.amazonaws.com/dev/robots.txt
          src: static/robots.txt
          path: /robots.txt
       -
          # https://123.execute-api.us-east-1.amazonaws.com/dev/browserconfig.xml
          src: static/browserconfig.xml
          path: /browserconfig.xml
```  

3 - Make api gateway act as a proxy to the S3 bucket for any static route requests such as `/robots.txt`, `/browserconfig.xml` etc.

*Do note* that you can only setup static routes for files inside the `static/` directory. 
 
Related: https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/29, https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/14
