### ISSUE TITLE
Is it possible to have other handlers/functions as well?

### ISSUE THREAD

**Issue by JAStanton** [danielcondemarin/serverless-nextjs-plugin#52]
Is it possible to serve nextjs as it's layed out in the example, but to have additional handlers, say nested under `/api/` url structure so that I can have my entire app + api live in one project?

I am new to this, but I expected something like this to work:

`serverless.yml`
```yaml
service: basic-next-serverless-app

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2

plugins:
  - serverless-nextjs-plugin
  - serverless-offline

custom:
  serverless-nextjs:
    nextConfigDir: "./"

package:
  exclude:
    - ./**

functions:
  app:
    handler: index.handler
    events:
      - http: 'ANY /api/'
      - http: 'ANY /api/{proxy+}'
```

`index.js`
```js
const _ = require('lodash');
const serverless = require('serverless-http');
const express = require('express');

app.get('/api/a-thing', async (req, res) => {
  res.json({ hey: 1 });
});

const serverlessApp = serverless(app);

export const handler = async (event, context) => {
  return await serverlessApp(event, context);
};
```

But instead I just get my react 404 page.
