### ISSUE TITLE
Support pages with similar names

### ISSUE THREAD

**Issue by Xiphe** [danielcondemarin/serverless-nextjs-plugin#67]
Given I have two nested pages
 - `pages/one/foo.js`
 - `pages/two/foo.js`

And I want to provide different [custom page routing](https://github.com/danielcondemarin/serverless-nextjs-plugin#custom-page-routing) configurations for these

Then I expect to write my custom pageConfig like this:

```yml
custom:
  serverless-nextjs:
    nextConfigDir: ./
    pageConfig:
      one/foo: #...
      two/foo: #...
```

But only the page file is used as a name, so I can not provide different configs for these.

I'd propose to use the relative page path as identifier in the custom config.

I'd be happy to provide a PR. But this change would be a braking change with the current API. Please let me know how to proceed.
