### ISSUE TITLE
Static files (robots.txt,...) error : PermanentRedirect

### ISSUE THREAD

**Issue by romainquellec** [danielcondemarin/serverless-nextjs-plugin#73]
```
<Error>
<Code>PermanentRedirect</Code>
<Message>
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
</Message>
<Endpoint>assets.cuistotducoin.com.s3.amazonaws.com</Endpoint>
<Bucket>assets.cuistotducoin.com</Bucket>
<RequestId>70179CC3BDA875DE</RequestId>
<HostId>
mZi2KGHgQ/Y+yicPFNcnTf+bt7PyxV2Tk0k6jv0iP38CCzIECxhPSoRXwuBYHrF8A1XZuI4bZPs=
</HostId>
</Error>
```

My serverless.yml config :
```
custom:
  sentry:
    dsn: ${env:SENTRY_DSN}
    organization: cuistotducoin
    project: front
  serverless-nextjs:
    assetsBucketName: assets.cuistotducoin.com
    staticDir: ./static
    routes:
      - src: ./static/robots.txt
        path: robots.txt
      - src: ./static/browserconfig.xml
        path: browserconfig.xml
      - src: ./static/manifest.json
        path: manifest.json
```

Full project : https://github.com/CuistotduCoin/front

Did I missed some rights ? Should I "reset" the stack ?
