### ISSUE TITLE
Static assets respond with 404

### ISSUE THREAD

**Issue by mattdell** [danielcondemarin/serverless-nextjs-plugin#88]
### Problem

Following the NextJS convention, I have a static folder in the root of my project. If I put in a file, I expect it to upload and be accessible to the application exactly as it is locally.

I've been looking at this for the better part of a day now and I can't get it to work. I see static asset support was introduced in version 1.6.0 and I've looked at the code change introduced in #54. I've tried versions 1.6.0 and the latest 1.8.1.

First, the files will only upload if I specify the `staticDir` in serverless.yml

```
custom:
  serverless-nextjs:
    nextConfigDir: ./
    staticDir: ./static
```

This doesn't seem necessary from the way I've comprehended the readme in that the static folder will be uploaded as long as I specify an `assetPrefix` in next.config.js.

> If you don't want to manage uploading the next static assets yourself, like uploading them to a CDN, the plugin can do this for you by hosting the asset files on S3.

Ignoring that, I'm fine to add `staticDir` in my serverless.yml. That at least uploads the files to my S3 bucket which I've defined in next.config.js

```
assetPrefix: isLocal ? '' : `https://${assetsBucketName}.s3-eu-west-1.amazonaws.com`,
```

But, when I reference the static file in my NextJS app the response is a 404.

<img width="1473" alt="Screenshot 2019-06-12 at 12 18 06" src="https://user-images.githubusercontent.com/2536442/59347290-274d1d80-8d0c-11e9-8ce0-34058e105504.png">

The file does exist in the S3 bucket if I navigate to https://${assetsBucketName}.s3-eu-west-1.amazonaws.com/static/apple-touch-icon.png

But if I navigate to https://mycustomdomain.com/static/apple-touch-icon.png then I get a 404.

What this looks like is that there is no routing happening in API Gateway to allow for a `/static` path so falls back to a 404.

So then I followed the suggestion towards the bottom in the static hosting section.

> If you need the static assets available in the main domain of your application, you can use the routes configuration to proxy API Gateway requests to S3. For example, to host /robots.txt:

This isn't exactly what I want to do, but I figured I'd try it anyway to at least see a proxy rule appear for this specific case.

```
custom:
  serverless-nextjs:
    nextConfigDir: ./
    staticDir: ./static
    routes:
      - src: ./static/apple-touch-icon.png
        path: apple-touch-icon.png
```

But again, I just see a 404.

![screencapture-favicon-front-end-pistonheads-apple-touch-icon-png-2019-06-12-12_16_52](https://user-images.githubusercontent.com/2536442/59347493-aa6e7380-8d0c-11e9-9853-daf2f50377ce.png)

So I'm out of ideas. 😕 

### Some code to help

serverless.yml
```yml

service: my-app

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  region: eu-west-1
  apiGateway:
    minimumCompressionSize: 1024

plugins:
  - serverless-dotenv-plugin
  - serverless-nextjs-plugin
  - serverless-domain-manager

custom:
  serverless-nextjs:
    nextConfigDir: ./
    staticDir: ./static
    routes:
      - src: ./static/apple-touch-icon.png
        path: apple-touch-icon.png
  customDomain:
    domainName: ${env:STAGE}-front-end.mydomain.com
    certificateName: 'mydomain.com'
    createRoute53Record: true

package:
  # exclude everything
  # page handlers are automatically included by the plugin
  exclude:
    - ./**

```

next.config.js
```js
const withPlugins = require('next-compose-plugins');
const withSass = require('@zeit/next-sass');
const withCss = require('@zeit/next-css');
const withBundleAnalyzer = require('@zeit/next-bundle-analyzer');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

require('dotenv').config();

const {
  ANALYZE_BUNDLE: analyzeBundle,
  IS_LOCAL: isLocal,
  STAGE: stage,
} = process.env;

const assetsBucketName = `${stage}-front-end-assets`;

module.exports = withPlugins(
  [
    [withCss],
    [
      withSass,
      {
        cssModules: true,
        cssLoaderOptions: {
          importLoaders: 1,
          localIdentName: isLocal ? '[name]__[local]--[hash:base64:6]' : '[hash:base64:6]',
        },
      },
    ],
    [
      withBundleAnalyzer,
      {
        analyzeServer: ['server', 'both'].includes(analyzeBundle),
        analyzeBrowser: ['browser', 'both'].includes(analyzeBundle),
        bundleAnalyzerConfig: {
          server: {
            analyzerMode: 'server',
            analyzerPort: 8888,
          },
          browser: {
            analyzerMode: 'server',
            analyzerPort: 8889,
          },
        },
      },
    ],
  ], {
    env: {
      STAGE: stage,
    },
    target: 'serverless',
    assetPrefix: isLocal ? '' : `https://${assetsBucketName}.s3-eu-west-1.amazonaws.com`,
    pageExtensions: ['tsx'],
    webpack(config, options) {
      if (options.isServer) {
        // Type checking on build
        config.plugins.push(new ForkTsCheckerWebpackPlugin());
      }

      return config;
    },
  },
);
```

_document.tsx
```tsx
import React from 'react';
import Document, { Head, Main, NextScript } from 'next/document';

import '../src/config/axios.config';

const bodyStyles = {
  margin: 0,
  padding: 0,
  fontFamily: '\'Open Sans\', sans-serif',
  WebkitFontSmoothing: 'antialiased',
  MozOsxFontSmoothing: 'grayscale',
  fontSize: '16px',
};

export default class CustomDocument extends Document {
  render() {
    return (
      <html lang="en-US">
        <Head>
          <title>My Site Title</title>
          <meta charSet="utf-8" />
          <link rel="apple-touch-icon" sizes="180x180" href="/static/apple-touch-icon.png" />
          <link rel="icon" type="image/png" sizes="32x32" href="/static/favicon-32x32.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="/static/favicon-16x16.png" />
          <link rel="manifest" href="/static/manifest.json" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" />
        </Head>
        <body style={bodyStyles}>
          <img src="/apple-touch-icon.png" />
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```

I'm entirely open to the idea that I'm doing something wrong. Help?
