### ISSUE TITLE
static assets respond with 403

### ISSUE THREAD

**Issue by fullstackdb** [danielcondemarin/serverless-nextjs-plugin#96]
### Issue:
When app published, - s3 bucket with static assets file successfully created, bucket itself has public access, apigateway and stack successfully created as well.
But when I'm reaching apigateway instance, I got 403 response for static assets files (see screenshot below).
![image](https://user-images.githubusercontent.com/25477677/60582445-7b8a7100-9d91-11e9-9985-8b4d58ed31fd.png)

### Debug Info:
serverless.yml
```
service: serverless-ssr-new-nextjs-plug

plugins:
  - serverless-nextjs-plugin
  - serverless-offline

frameworkVersion: ">=1.21.0 <2.0.0"

custom:
  serverless-nextjs:
    nextConfigDir: ./
    # staticDir: 'https://s3.amazonaws.com/trymeoutgetitwork'
    assetsBucketName: "trymeoutgetitwork"
    cloudFront: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: development
  region: us-east-1

package:
  exclude:
    - ./**

```

next.config.js
```
module.exports = {
  target: "serverless",
  assetPrefix: 'https://s3.amazonaws.com/trymeoutgetitwork'
};
```
package-lock:
```
 "serverless-nextjs-plugin": {
      "version": "2.1.0-alpha.0",
      "resolved": "https://registry.npmjs.org/serverless-nextjs-plugin/-/serverless-nextjs-plugin-2.1.0-alpha.0.tgz",
      "integrity": "sha512-hmcEvJzBaJ41VVfjTWlhzSPceRkoflSCI6uS1Aobmz6Sx5XP4Ng96EiTBIidV8CkuYXuE4znbafBmk3qkxhhwQ==",
```
Waited on https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/89 to solve this issue, but got the same response. 

### Comments:
Thank you @mattdell  for your input, especially https://github.com/danielcondemarin/serverless-nextjs-plugin/pull/92

But even with `"serverless-nextjs-plugin": "2.1.0-alpha.0",` I can't see assets routes in my apigateway Resources as expected.
![image](https://user-images.githubusercontent.com/25477677/60583006-914c6600-9d92-11e9-8e5e-753196e2c7af.png)

Looks like I'm missing something obvious.
Would be grateful for any help.
